# Generated by Django 4.1.6 on 2023-02-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dive_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('site_city', models.CharField(max_length=50)),
                ('site_state', models.CharField(blank=True, max_length=50)),
                ('site_country', models.CharField(max_length=50)),
                ('site_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diver.diver')),
            ],
        ),
    ]
