# Generated by Django 4.1.6 on 2023-02-13 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='pd_review_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 16, 58, 40, 41815)),
        ),
    ]
