# Generated by Django 4.1.6 on 2023-02-12 10:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dive_site', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DS_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 12, 4, 13, 14, 638254))),
                ('review_text', models.CharField(max_length=500)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dive_site.dive_site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
