# Generated by Django 4.1.6 on 2023-02-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diver', '0001_initial'),
        ('dive_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DS_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=500)),
                ('diver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diver.diver')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dive_site.dive_site')),
            ],
        ),
    ]
