# Generated by Django 4.1.6 on 2023-02-13 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ds_review',
            name='review_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 13, 16, 58, 40, 39312)),
        ),
    ]
