# Generated by Django 4.1.6 on 2023-02-12 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ds_review',
            old_name='site_id',
            new_name='site',
        ),
        migrations.AlterField(
            model_name='ds_review',
            name='review_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 12, 4, 27, 32, 845156)),
        ),
    ]
