# Generated by Django 4.1.6 on 2023-02-12 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_review', '0002_rename_site_id_ds_review_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ds_review',
            old_name='site',
            new_name='dive_site',
        ),
        migrations.AlterField(
            model_name='ds_review',
            name='review_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 12, 4, 31, 28, 742578)),
        ),
    ]
