# Generated by Django 4.1.6 on 2023-02-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diver',
            name='user_availibilty',
            field=models.BooleanField(default=False),
        ),
    ]
