# Generated by Django 4.1.6 on 2023-02-10 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_product_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_author',
            new_name='user',
        ),
    ]
